name: services
description: "Package responsável pela inicializção dos serviços básicos da aplicação"
version: 0.1.0
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.3
  cloud_firestore: ^4.17.1
  firebase_remote_config: ^4.3.14
  return_success_or_error: ^0.18.0
  get: ^4.6.6
  connectivity_plus: ^6.0.3
  path_provider: ^2.1.2
  hive: ^4.0.0-dev.2
  permission_handler: ^11.3.1
  android_power_manager: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
