name: painel_configure_ed
description: "Painel de controle para o app Android Configure ED."
publish_to: 'none' 
version: 0.1.0
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  #Dependencias internas
  dependencies_module:
    path: ../../modulos/dependencies_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
