name: services
description: "Package responsável pela inicializção dos serviços básicos da aplicação"
version: 0.1.0
publish_to: 'none'
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies_module:
    path: ../dependencies_module
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter:
