name: auth
description: "Modulo responsavel pela autenticação"
version: 0.0.1
publish_to: 'none'
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../dependencies
  google_sign_in_web: ^0.12.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
